.travis.yml
=> travis: initial configuration

README.rst
=> docs: addition of Travis CI badge

html/index.html
=> docs: move to readthedocs.io

base/static/css/style.css, base/templates/header.html
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> header: better responsive menu

base/templates/pages/gettingstarted.html
=> gettingstarted: git clone example fix

base/static/css/style.css
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>
=> minor: hovering fix in carousel

base/templates/index.html
=> home: carousel text improvements

README.rst, docker-compose.yml
* Introduces nginx access logs on host for production site. (closes #24)
=> nginx: access logs on host

base/sites/desy.json, base/sites/gsi.json, base/sites/julich.json, base/sites/mlz.json
Update texts for join2 (http://join2.de) repositories to the official
version and add project reference.
Signed-off-by: Alexander Wagner <alexander.wagner@desy.de>
Addresses join2/join2-data#1438
=> sites: update join2 texts

base/sites/hepdata.json
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> sites: updated hepdata url

templates/community.html, templates/footer_contact.html, templates/header.html, templates/index.html, templates/showcase.html, templates/showcase_add.html
Use right way to generate asset url
=> fix asseturl

templates/footer_contact.html
=> templates: reorder footer menu

assets/static/css/style.css
* close #19 
If a link in the navbar or in the footer is hover, it becomes white:
=> assets: change link hovering colour

README.rst, templates/gettingstarted.html
Closes https://github.com/inveniosoftware/inveniosoftware.org/issues/48, https://github.com/inveniosoftware/inveniosoftware.org/issues/45
=> docs: fix broken links

.travis.yml, README.rst
=> Deploy and docs fixes

assets/static/css/style.css, templates/blog.html, templates/macros/blog-list-item.html, templates/macros/blog-top.html
Addresses https://github.com/inveniosoftware/inveniosoftware.org/issues/56
=> blog: 3 column layout

templates/index.html, templates/page.html, templates/trackingcode.html
=> templates: add piwik script

assets/static/css/style.css, templates/blog-post.html, templates/macros/blog.html
Closes https://github.com/inveniosoftware/inveniosoftware.org/issues/74
=> blog: fix titles links

assets/static/css/style.css, content/roadmap/contents.lr, content/roadmap/data-citation/contents.lr, content/roadmap/deposit-bundle/contents.lr, content/roadmap/files-bundle/contents.lr, content/roadmap/i18n/contents.lr, content/roadmap/ils/contents.lr, content/roadmap/iugw-2019/contents.lr, content/roadmap/javascript-framework/contents.lr, content/roadmap/license-change/contents.lr, content/roadmap/ngr/contents.lr, content/roadmap/rdm/contents.lr, content/roadmap/statistics-bundle/contents.lr, content/roadmap/v3.0-release/contents.lr, content/roadmap/v3.1-release/contents.lr, models/roadmap-card.ini, models/roadmap.ini, templates/header.html, templates/macros/roadmap-card.html, templates/roadmap-card.html, templates/roadmap.html
=> ui: add roadmap page

templates/index.html
=> index: fix getting started 3 column alignment

assets/static/css/style.css, content/legacy/contents.lr, models/legacy.ini, templates/index.html, templates/legacy.html
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>
=> Text and style for feat and built

assets/static/img/logo-python.svg, templates/index.html
=> opensource: add Python logo

assets/static/css/style.css, templates/gettingstarted.html, templates/index.html
* Adds "Get started" three boxes on the home page and updates the standalone
`/gettingstarted` page. (addresses #53)
=> gettingstarted: three boxes and text updates

templates/showcase_add.html
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>
=> examples: fix add example doc

templates/index.html
=> frontpage: fix typo

content/blog/invenio-v33-released/contents.lr
Closes https://github.com/inveniosoftware/inveniosoftware.org/issues/121
**REQUIRES**
=> blog: sketch invenio 3.3 post

README.rst, assets/static/css/style.css, content/blog/2017-08-11-invenio-sprint/contents.lr, content/blog/2017-10-20-invenio-sprint/contents.lr, content/blog/2017-12-01-invenio-sprint/contents.lr, content/blog/2018-03-23-invenio-sprint/contents.lr, content/blog/2018-05-28-invenio-sprint/contents.lr, content/blog/2019-10-15-web-redesign/contents.lr, content/documentation/contents.lr, templates/about.html, templates/documentation.html, templates/footer_contact.html, templates/getinvolved.html, templates/header.html, templates/index.html, templates/products/ils.html, templates/products/rdm.html, templates/support.html
* closes inveniosoftware/inveniosoftware.org#133
* addresses inveniosoftware/opensource#67
See also:
- [Preview on small screens](https://user-images.githubusercontent.com/9027075/90748247-3812ff00-e2d2-11ea-9382-7a7e81f9ce7b.png)
- [Preview on extra small screens](https://user-images.githubusercontent.com/9027075/90748312-4eb95600-e2d2-11ea-916b-767599d02974.png)
([old version](https://user-images.githubusercontent.com/9027075/90616038-35020b00-e20d-11ea-983e-89bbe414512b.png))
=> Add documentation page with search

content/blog/2021-02-10-onboarding-resource-roundup/contents.lr
Request review from @fenekku, @lnielsen, @jbenito3
=> Add Onboarding Resource Roundup Blog post

content/blog/2022-07-06-OR2022-spotlight/contents.lr
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> Add OR2022 Spotlight blog post

templates/trackingcode.html
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> enable matomo tracking code

content/blog/2023-05-30-may-curation-validation/contents.lr
Request review from @lnielsen @jbenito3 @fenekku @carsonicator
=> Add May 2023 Blog post

databags/sites.json
The original PR was a WIP merged before @carsonicator could take a look. This contains the required edits.
=> showcase: edit Prism description

assets/static/css/style.css, content/people/alexandros-ioannidis/contents.lr, content/people/audun-bjorkoy/contents.lr, content/people/esteban-gabancho/contents.lr, content/people/guillaume-viger/contents.lr, content/people/hakan-bayindir/contents.lr, content/people/jose-benito-gonzalez/contents.lr, content/people/kai-woerner/contents.lr, content/people/karolina-przerwa/contents.lr, content/people/kristi-holmes/contents.lr, content/people/lars-holm-nielsen/contents.lr, content/people/matthew-carson/contents.lr, content/people/nicola-tarocco/contents.lr, content/people/pablo-panero/contents.lr, content/people/rodrigo-lopes-de-almeida/contents.lr, content/people/sara-gonzales/contents.lr, content/people/tibor-simko/contents.lr, content/people/tom-morrell/contents.lr, content/people/werner-gresshoff/contents.lr, content/people/zaharias-zaharodimos/contents.lr, models/person.ini, templates/people.html
The "Chat with me" links in the [People page](https://inveniosoftware.org/people/) are broken and we do not use Gitter anymore.
This pull request removes the chat field from the person model, from the content, and from the template.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributi …
=> people: remove broken Gitter chat links

templates/products/rdm.html
=> rdm: link to v12 release

templates/products/rdm.html
Fix broken v12 link described in https://github.com/inveniosoftware/inveniosoftware.org/issues/215
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s …
=> rdm: fix v12 link

databags/sites.json
Remove sites with broken links identified in https://github.com/inveniosoftware/inveniosoftware.org/issues/204. I've done an additional check and haven't been able to identify replacements.
I also changed all the "repository" tags to "institutional-repository", since that's what's actually used with the Repository facet https://github.com/inveniosoftware/inveniosoftware.org/blob/7be488af582efebce98ce09cf50c6beeaabc8a97/templates/menu.html
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an …
=> sites: remove sites with broken links and update repository tags

templates/products/rdm.html
=> fix: update content

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/publish.yml, .travis.yml, README.rst
In debugging the badge, I noticed that we're getting warnings about deprecated commands. Updating to more modern action versions should fix the issue.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current …
=> Update workflow versions
